require 'rake/testtask'
require 'rubygems/package_task'

require File.join(File.dirname(__FILE__), 'lib', 'active_support', 'version')
require File.expand_path('../../railslts-version/lib/railslts-version', __FILE__)

PKG_BUILD     = ENV['PKG_BUILD'] ? '.' + ENV['PKG_BUILD'] : ''
PKG_NAME      = 'activesupport'
PKG_VERSION   = RailsLts::VERSION::STRING + PKG_BUILD
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

RELEASE_NAME  = "REL #{PKG_VERSION}"

RUBY_FORGE_PROJECT = "activesupport"
RUBY_FORGE_USER    = "webster132"

test_files = FileList['test/**/*_test.rb']

if RUBY_VERSION < '3'
 test_files = test_files.exclude('test/ruby_3/**/*_test.rb')
end

task :default => :test
Rake::TestTask.new { |t| 
  t.libs << "test"
  t.pattern = test_files
  t.verbose = true
  t.warning = false
}

# Create compressed packages
dist_dirs = [ "lib", "test"]

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.summary = "Support and utility classes used by the Rails framework."
  s.description = %q{Utility library which carries commonly used classes and goodies from the Rails framework}

  s.files = [ "CHANGELOG", "README", "LICENSE" ] + Dir.glob( "lib/**/*" ).delete_if { |item| item.include?( "\.svn" ) }
  s.require_path = 'lib'
  s.has_rdoc = true

  s.author = "David Heinemeier Hansson"
  s.email = "david@loudthinking.com"
  s.homepage = "http://www.rubyonrails.org"
  s.rubyforge_project = "activesupport"
end

package_task = Gem::PackageTask
package_task.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

namespace :tzinfo do
  desc "Update bundled tzinfo gem. Only copies the subset of classes and definitions required to support Rails time zone features."
  task :update => ['tzinfo:copy_classes', 'tzinfo:copy_definitions'] do
    Rake::Task['tzinfo:cleanup_tmp'].invoke
  end
  
  task :unpack_gem do
    mkdir_p "tmp"
    cd "tmp"
    sh "gem unpack --version #{ENV['VERSION'] || "'> 0'"} tzinfo"
    cd ".."
  end
  
  task :copy_classes => :unpack_gem do
    mkdir_p "#{destination_path}/tzinfo"
    cp "#{tmp_path}/lib/tzinfo.rb", destination_path
    comment_requires_for_excluded_classes!('tzinfo.rb')
    files = FileList["#{tmp_path}/lib/tzinfo/*.rb"]
    files.each do |file|
      filename = File.basename(file)
      unless excluded_classes.include? filename.sub(/.rb$/, '')
        cp "#{tmp_path}/lib/tzinfo/#{filename}", "#{destination_path}/tzinfo"
        comment_requires_for_excluded_classes!("tzinfo/#{filename}")
      end
    end
  end
  
  task :copy_definitions => :unpack_gem do
    $:.unshift "#{File.dirname(__FILE__)}/lib"
    require 'active_support/values/time_zone'
    definitions_path = "#{destination_path}/tzinfo/definitions/"
    mkdir_p definitions_path
    ActiveSupport::TimeZone::MAPPING.values.each do |zone|
      subdir = nil
      if /\// === zone
        subdir = zone.sub(/\w+$/, '')
        mkdir_p "#{definitions_path}/#{subdir}"
      end
      cp "#{tmp_path}/lib/tzinfo/definitions/#{zone}.rb", "#{definitions_path}/#{subdir}"
    end
  end

  task :cleanup_tmp do
    rm_rf "tmp"
  end
  
  def comment_requires_for_excluded_classes!(file)
    lines = open("#{destination_path}/#{file}") {|f| f.readlines}
    updated = false
    
    new_lines = []
    lines.each do |line|
      if Regexp.new("require 'tzinfo/(#{excluded_classes.join('|')})'") === line
        updated = true
        new_lines << "# #{line}"
      else
        new_lines << line
      end
    end
    
    if updated
      open("#{destination_path}/#{file}", "w") {|f| f.write(new_lines.join)}
    end
  end
  
  def version
    ENV['VERSION'] ||= get_unpacked_version
  end
  
  def get_unpacked_version
    m = (FileList["tmp/tzinfo-*"].to_s.match /\d+\.\d+\.\d+/)
    m ? m[0] : raise(LoadError, "TZInfo gem must be installed locally. `gem install tzinfo` and try again")
  end
  
  def tmp_path
    "tmp/tzinfo-#{version}"
  end
  
  def destination_path
    "lib/active_support/vendor/tzinfo-#{version}"
  end
  
  def excluded_classes
    %w(country country_index_definition country_info country_timezone timezone_index_definition timezone_proxy tzdataparser)
  end
end
